# BootPartition.cmake - Relink colecojam for the pico-bootLoader app partition.
#
# The pico-bootLoader (https://github.com/fhoedemakers/pico-bootLoader) owns the
# first 512 KB of flash and stays resident; everything after it is an
# application partition. To be launchable from its picker, colecojam must link
# with FLASH ORIGIN=0x10080000 instead of the RP2350 default 0x10000000, so the
# loader can write the UF2 verbatim and jump to it.
#
# Flash map (Adafruit Fruit Jam, 16 MB):
#
#   0x10000000  bootloader                    (512 KB)
#   0x10080000  application partition         (15.5 MB)   <- we link here
#   0x11000000  end of flash
#
# This is the same job pico_shared/BootPartition.cmake and pico-doom's vendored
# copy do, but neither of those works here, for two reasons:
#
#   1. They call pico_set_linker_script() with a patched memmap_DEFAULT.ld. That
#      overrides the binary type, so our pico_set_binary_type(copy_to_ram) would
#      be silently discarded and the image would run from XIP again -- which is
#      exactly what breaks pico_hdmi's core-1 scanline timing. The whole point
#      of copy_to_ram here. See the comment at the bottom of ../CMakeLists.txt.
#
#   2. They only know the pre-2.3.0 SDK layout. SDK 2.3.0 moved the memory maps
#      to src/rp2350/pico_platform/ and turned them into chains of .incl
#      fragments, so there is no FLASH(rx) line left to patch -- the candidate
#      list misses and the helper dies with a FATAL_ERROR.
#
# So: on SDK >= 2.3.0 use the supported override-path API, which replaces just
# the generated pico_flash_region.ld fragment and leaves the binary type alone.
# On older SDKs fall back to patching the memmap for THIS target's binary type.

if(DEFINED _COLECO_BOOTPARTITION_INCLUDED)
    return()
endif()
set(_COLECO_BOOTPARTITION_INCLUDED 1)

set(COLECO_APP_BASE    "0x10080000" CACHE STRING "pico-bootLoader app-partition base")
set(COLECO_APP_SIZE    "0xF80000"   CACHE STRING "App partition size (15.5 MB of 16 MB)")
set(COLECO_FLASH_TOTAL "0x1000000"  CACHE STRING "Total external flash on the board (Fruit Jam = 16 MB)")

# ---------------------------------------------------------------------------
# _coleco_relink_via_flash_region(<target> <dir>)
#
# SDK >= 2.3.0. Every RP2350 memory map -- memmap_default.ld and
# memmap_copy_to_ram.ld alike -- reaches its FLASH region through
# memory_flash.incl, which is nothing but:
#
#     MEMORY { INCLUDE "pico_flash_region.ld" }
#
# The SDK generates that fragment into its own build dir and puts it on the
# linker's search path. pico_add_linker_script_override_path() prepends another
# -L ahead of it (pico_standard_link/CMakeLists.txt emits the override paths
# before PICO_LINKER_SCRIPT_INCLUDE_DIRS), so ours is found first. Nothing else
# about the link changes.
# ---------------------------------------------------------------------------
function(_coleco_relink_via_flash_region TARGET DIR)
    file(WRITE "${DIR}/pico_flash_region.ld"
         "/* Generated by cmake/BootPartition.cmake - do not edit.\n"
         " * Overrides the SDK's generated fragment of the same name to move the\n"
         " * image into the pico-bootLoader application partition. */\n"
         "FLASH(rx) : ORIGIN = ${COLECO_APP_BASE}, LENGTH = ${COLECO_APP_SIZE}\n")
    pico_add_linker_script_override_path(${TARGET} "${DIR}" FILES pico_flash_region.ld)
    message(STATUS
        "BootPartition: ${TARGET} -> FLASH ORIGIN=${COLECO_APP_BASE} "
        "LENGTH=${COLECO_APP_SIZE} (pico_flash_region.ld override)")
endfunction()

# ---------------------------------------------------------------------------
# _coleco_relink_via_memmap_patch(<target> <dir>)
#
# SDK 2.1 / 2.2. Copy the SDK memory map for this target's binary type, rewrite
# only the FLASH(rx) region, and hand the copy to pico_set_linker_script().
#
# Picking the map by binary type is the part the upstream helpers get wrong:
# with copy_to_ram selected, patching memmap_default.ld produces a perfectly
# valid XIP image at the right address and no warning of any kind.
# ---------------------------------------------------------------------------
function(_coleco_relink_via_memmap_patch TARGET DIR)
    get_target_property(_bt ${TARGET} PICO_TARGET_BINARY_TYPE)
    if(NOT _bt)
        set(_bt "${PICO_DEFAULT_BINARY_TYPE}")
    endif()
    if(NOT _bt)
        set(_bt "default")
    endif()

    set(_candidates
        "${PICO_SDK_PATH}/src/rp2_common/pico_crt0/rp2350/memmap_${_bt}.ld"
        "${PICO_SDK_PATH}/src/rp2_common/pico_standard_link/memmap_${_bt}.ld"
    )
    set(_src_ld "")
    foreach(_c IN LISTS _candidates)
        if(EXISTS "${_c}")
            set(_src_ld "${_c}")
            break()
        endif()
    endforeach()
    if(_src_ld STREQUAL "")
        message(FATAL_ERROR
            "BootPartition: no RP2350 memmap_${_bt}.ld found under ${PICO_SDK_PATH}. "
            "Build for the rp2350 platform with Pico SDK >= 2.1.0.")
    endif()

    file(READ "${_src_ld}" _ld_text)

    # 2.2 pulls the FLASH region in from a generated pico_flash_region.ld that
    # carries the board's full flash size; replace that INCLUDE with an explicit,
    # capped region so an image overflowing its partition is a link error rather
    # than something the loader has to reject at runtime.
    string(REPLACE
        "INCLUDE \"pico_flash_region.ld\""
        "FLASH(rx) : ORIGIN = ${COLECO_APP_BASE}, LENGTH = ${COLECO_APP_SIZE}"
        _ld_text "${_ld_text}")
    # 2.1 spells the region out inline; rewrite that form too (a no-op if the
    # replacement above already produced this line).
    string(REGEX REPLACE
        "FLASH\\(rx\\)[ \t]*:[^\n]*"
        "FLASH(rx) : ORIGIN = ${COLECO_APP_BASE}, LENGTH = ${COLECO_APP_SIZE}"
        _ld_text "${_ld_text}")

    # Fail loudly. An unpatched map links at 0x10000000, the UF2 is then rejected
    # by the loader's validate pass, and the on-screen diagnostic points at the
    # image rather than at this file.
    if(NOT _ld_text MATCHES "ORIGIN = ${COLECO_APP_BASE}")
        message(FATAL_ERROR
            "BootPartition: could not relocate FLASH in ${_src_ld}. Neither the "
            "pico_flash_region.ld INCLUDE nor an inline FLASH(rx) line was found, "
            "so the image would silently link at 0x10000000 and the bootloader "
            "could not launch it.")
    endif()

    set(_out_ld "${DIR}/${TARGET}_bootloader_memmap.ld")
    file(WRITE "${_out_ld}" "${_ld_text}")
    pico_set_linker_script(${TARGET} "${_out_ld}")
    message(STATUS
        "BootPartition: ${TARGET} -> FLASH ORIGIN=${COLECO_APP_BASE} "
        "LENGTH=${COLECO_APP_SIZE} (patched ${_bt} memmap)")
endfunction()

# ---------------------------------------------------------------------------
# coleco_offset_for_bootloader(<target>)
#
# Public entry point. Must be called after the target exists, after
# pico_sdk_init(), after pico_set_binary_type(), and before
# pico_add_extra_outputs().
# ---------------------------------------------------------------------------
function(coleco_offset_for_bootloader TARGET)
    set(_dir "${CMAKE_CURRENT_BINARY_DIR}/${TARGET}_bootpartition")
    file(MAKE_DIRECTORY "${_dir}")

    if(COMMAND pico_add_linker_script_override_path)
        _coleco_relink_via_flash_region(${TARGET} "${_dir}")
    else()
        _coleco_relink_via_memmap_patch(${TARGET} "${_dir}")
    endif()

    target_compile_definitions(${TARGET} PRIVATE
        # The board header may understate the chip; COLECO_FLASH_TOTAL is the
        # single source of truth, and flash_range_erase/program hard_assert on a
        # mismatch.
        PICO_FLASH_SIZE_BYTES=${COLECO_FLASH_TOTAL}
        BUILD_FOR_BOOTLOADER=1)

    # picotool >= 2.2.0 re-detects the chip from the ELF instead of trusting
    # --family, and assumes RP2040 for any image that does not start at
    # 0x10000000 -- which, by construction, ours does not.
    if(PICO_PLATFORM MATCHES "rp2350")
        set_target_properties(${TARGET} PROPERTIES
            PICOTOOL_EXTRA_UF2_ARGS "--platform;rp2350")
    endif()
endfunction()
